### PR TITLE
Post

### PR DESCRIPTION
**Pull request by james-logan**
added lodash
added the post model, the post tests (almost done), and the post routes (currently incomplete).

### CODE REVIEW

**Comment by james-logan** [comment]
@sscotth DOIT plz

**Comment by sscotth** [comment]
@james-logan This branch has conflicts that must be resolved

**Comment by sscotth** [comment]
Not sure why travis didn't run on this, but:

```
app/index.js
   8:42  error  Missing semicolon  semi
  10:40  error  Missing semicolon  semi
  22:52  error  Missing semicolon  semi

app/post/Post.js
   1:1    error  Use the global form of "use strict"  strict
   1:43   error  Missing semicolon                    semi
   2:26   error  Missing semicolon                    semi
  26:2    error  Missing semicolon                    semi
  34:101  error  Missing semicolon                    semi
  35:2    error  Missing semicolon                    semi
  54:22   error  Missing semicolon                    semi

app/post/post.routes.js
   9:27  error  Missing semicolon                 semi
  10:3   error  Missing semicolon                 semi
  15:4   error  Missing semicolon                 semi
  17:28  error  result is defined but never used  no-unused-vars
  18:15  error  Unexpected console statement      no-console
  18:31  error  Missing semicolon                 semi
  21:5   error  Missing semicolon                 semi
  23:3   error  Missing semicolon                 semi
  25:24  error  Missing semicolon                 semi

app/post/post_test.js
   2:1   error  Use the global form of "use strict"  strict
  21:30  error  Missing semicolon                    semi
  23:22  error  Missing semicolon                    semi
  43:5   error  Missing semicolon                    semi
  45:9   error  id is defined but never used         no-unused-vars
  48:30  error  Missing semicolon                    semi
  50:22  error  Missing semicolon                    semi
  57:11  error  Missing semicolon                    semi
  59:9   error  Missing semicolon                    semi
  60:7   error  Missing semicolon                    semi
  61:5   error  Missing semicolon                    semi
  68:32  error  Missing semicolon                    semi
  69:34  error  result is defined but never used     no-unused-vars
  73:13  error  Missing semicolon                    semi
  74:11  error  Missing semicolon                    semi
  75:9   error  Missing semicolon                    semi
  76:7   error  Missing semicolon                    semi
  77:5   error  Missing semicolon                    semi
  83:28  error  Missing semicolon                    semi
  85:53  error  Missing semicolon                    semi
  87:11  error  Missing semicolon                    semi
  88:9   error  Missing semicolon                    semi
  90:7   error  Missing semicolon                    semi
  91:5   error  Missing semicolon                    semi
  93:3   error  Missing semicolon                    semi
```

Also, remove the excess spacing and commented code

**Comment by james-logan** [comment]
@sscotth added all the semicolons and use stricts

**Comment by sscotth** [comment]
Can you sync your fork and fix the conflict in package.json?
https://help.github.com/articles/syncing-a-fork/

**Comment by sscotth** [comment]
Look over my changes and let me know if you have any questions tomorrow.

**Pull request merged**
