### PR TITLE
Logan branch

### PR DESCRIPTION
**Pull request by ldougher06**
Got first test passing. Suggestions?

### CODE REVIEW

**Comment by sscotth** [comment]
Can you describe your pull request in the title? What feature is this pull request for?

**Comment by ldougher06** [comment]
Our test shows that we can post to a specified collection and retrieve the entire post object or just the username etc. We can use this to match a mentioned username with the correct user object where the user's email would be available.

**Comment by sscotth** [comment]
By title of the pull request, I mean what is currently "Logan branch"

Be more descriptive

**Comment by sscotth** [comment]
Closing in favor of #57

**Pull request closed without merging**
